### ISSUE TITLE
Could you add CQT and iCQT?

### ISSUE THREAD

**Issue by turian** [sp-nitech/diffsptk#31]

**Comment by takenori-y** [comment]
CQT has already implemented.
https://github.com/sp-nitech/diffsptk/blob/master/diffsptk/core/cqt.py

Please let me know if you know good implementation or papers about iCQT.

**Comment by turian** [comment]
Librosa has an iCQT implementation: https://librosa.org/doc/latest/_modules/librosa/core/constantq.html#icqt

**Comment by takenori-y** [comment]
Thank you for sharing the link but the implementation is quite complicated. I currently cannot guarantee that I will implement the iCQT module.

**Comment by takenori-y** [comment]
Added in the v2 branch.

They are based on librosa == 0.9.2 as I was not able to use librosa >= 0.10.0.
