### ISSUE TITLE
typo: "lienar_intpl" in the docstring of `LinearInterpolation`

### ISSUE THREAD

**Issue by yoyololicon** [sp-nitech/diffsptk#48]
https://github.com/sp-nitech/diffsptk/blob/9f8131b9f26eef3bb518ca3ee3844f59c66cc64a/diffsptk/core/linear_intpl.py#L24-L25
Is it supposed to be `linear_intpl`?

BTW, the repository description on GitHub is "A _differential_ version of SPTK".
I guess it should be "A _differentiable_ ..." which you also used in the README file.

**Comment by takenori-y** [comment]
Thank you for pointing these out!
I have fixed them.
