### ISSUE TITLE
Any plan for a `functional` module?

### ISSUE THREAD

**Issue by yoyololicon** [sp-nitech/diffsptk#65]
Hi, as the title said, is there any plan to provide a `functional` module, like PyTorch did, for some state-less transformations?
For example, conversion functions like `lar2par`, `par2lpc`, `levdur`, and so on depend on an `order` parameter that can be inferred from the input data. 
Having them as pure functions would be great without creating a `nn.Module` instance.
It would also be cool to have equivalent functional counterparts of other transforms, with default arguments that work out of the box when chaining the functions, similar to how `librosa` does.

**Comment by takenori-y** [comment]
If I can write the functional modules in a sophisticated way, it will be released as version 2.0.
I'll try, but sorry if it doesn't work.

**Comment by yoyololicon** [comment]
I think we can first transfer some easy ones (those I mentioned above). Just moving `forward` into a standalone function. Should be straightforward.
I can make a draft PR based on this idea. Let me know if that works. 😀

**Comment by takenori-y** [comment]
I made a PR for this issue (#66).
Please use the v2 branch and reopen this issue if you find any problems.

**Comment by yoyololicon** [comment]
Thanks for the quick and timely help! I'll definitely try out the v2 branch. Thanks a lot!
